In [1]:
print("hello eorld")

hello eorld

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame({
    "Name":["Aman","Saurav","Karan","subham","Abhishek",None,"Sameer"],
    "Age":[22,54,None,54,54,59,25],
    "Marks":[85,None,88,89,89,69,None],
    "Subject":["Math","phy","chem","chem","Math","phy","chem"]
})
df

       Name   Age  Marks Subject
0      Aman  22.0   85.0    Math
1    Saurav  54.0    NaN     phy
2     Karan   NaN   88.0    chem
3    subham  54.0   89.0    chem
4  Abhishek  54.0   89.0    Math
5      None  59.0   69.0     phy
6    Sameer  25.0    NaN    chem

In [ ]:
print(df.shape)

(7, 4)

In [ ]:
print(df.dtypes)

Name        object
Age        float64
Marks      float64
Subject     object
dtype: object

In [ ]:
print(df[["Name","Marks"]])

In [ ]:
print(df[["Marks"]]>80)

In [ ]:
filtered_students = df[(df["Age"] > 22) & (df["Marks"] > 80)]
filtered_students

In [ ]:
df["Subject"].value_counts()

In [ ]:
df_sort = df.sort_values(by="Marks", ascending=False)
df_sort

In [ ]:
top_2 = df.nlargest(2, "Marks")
top_2

In [ ]:
lowest = df.nsmallest(1, "Marks")
lowest

In [ ]:
df.isna().sum()

In [ ]:
df[df["Marks"].isna()]

In [ ]:
cleaned_data=df.dropna()
cleaned_data

In [ ]:
print(df.shape)

In [ ]:
print(cleaned_data.shape)

In [ ]:
#EX5.

#1.None in numeric column becomes nan which is float type.
#2.It will alter the original data which may lead to data inconsistency
#3.Handel the missing values

EX2

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Saurav", None, "Shubham", "Abhishek",
             None, "Rohit", "Priya", "Neha", "Arjun"],
    
    "Department": ["IT", "HR", "Finance", "IT", "Marketing",
                   "HR", "Finance", "IT", "Marketing", "HR"],
    
    "Role": ["Developer", "Recruiter", "Accountant", "Tester", "SEO Specialist",
             "HR Manager", "Financial Analyst", "Accountant", "Tester", "HR Executive"],
    
    "Experience": [2, 5, 3, 0, 4, 6, 1, 0, 2, 5],
    
    "Salary": [40000, 55000, 50000, 35000, 45000,
               60000, 48000, 42000, 39000, 52000],
    
    "Score": [85, 78, 88, None,90, 76, 84, None, 75, 89]
})

df

       Name Department               Role  Experience  Salary  Score
0      Aman         IT          Developer           2   40000   85.0
1    Saurav         HR          Recruiter           5   55000   78.0
2      None    Finance         Accountant           3   50000   88.0
3   Shubham         IT             Tester           0   35000    NaN
4  Abhishek  Marketing     SEO Specialist           4   45000   90.0
5      None         HR         HR Manager           6   60000   76.0
6     Rohit    Finance  Financial Analyst           1   48000   84.0
7     Priya         IT         Accountant           0   42000    NaN
8      Neha  Marketing             Tester           2   39000   75.0
9     Arjun         HR       HR Executive           5   52000   89.0

In [5]:
df.groupby("Department")["Salary"].mean()

Department
Finance      49000.000000
HR           55666.666667
IT           39000.000000
Marketing    42000.000000
Name: Salary, dtype: float64

In [6]:
df.groupby("Department")["Salary"].mean()

Department
Finance      49000.000000
HR           55666.666667
IT           39000.000000
Marketing    42000.000000
Name: Salary, dtype: float64

In [7]:
df.groupby("Department")["Score"].count()

Department
Finance      2
HR           3
IT           1
Marketing    2
Name: Score, dtype: int64

In [8]:
df.groupby("Department").size()

Department
Finance      2
HR           3
IT           3
Marketing    2
dtype: int64

In [9]:
df.groupby('Department')['Salary'].agg(['mean','max','min'])

                    mean    max    min
Department
Finance     49000.000000  50000  48000
HR          55666.666667  60000  52000
IT          39000.000000  42000  35000
Marketing   42000.000000  45000  39000

In [10]:
df.groupby('Department')['Score'].agg(['mean','max','min','count'])

            mean   max   min  count
Department
Finance     86.0  88.0  84.0      2
HR          81.0  89.0  76.0      3
IT          85.0  85.0  85.0      1
Marketing   82.5  90.0  75.0      2

In [13]:
df.groupby(["Department","Role"])["Salary"].mean()

Department  Role
Finance     Accountant           50000.0
            Financial Analyst    48000.0
HR          HR Executive         52000.0
            HR Manager           60000.0
            Recruiter            55000.0
IT          Accountant           42000.0
            Developer            40000.0
            Tester               35000.0
Marketing   SEO Specialist       45000.0
            Tester               39000.0
Name: Salary, dtype: float64

In [14]:
df.groupby(["Department","Experience"])["Salary"].mean()

Department  Experience
Finance     1             48000.0
            3             50000.0
HR          5             53500.0
            6             60000.0
IT          0             38500.0
            2             40000.0
Marketing   2             39000.0
            4             45000.0
Name: Salary, dtype: float64